#!/bin/bash
#install additional python packages
conda install -y scikit-learn
conda install -y -c conda-forge tifffile
conda install -y  memory_profiler
conda install -y libiconv
conda install -y -c conda-forge umap-learn
conda install -y -c https://conda.anaconda.org/biocore scikit-bio
conda install -y -c conda-forge openslide
conda install -y -c conda-forge openslide-python
conda install -y -c conda-forge mahotas
conda update -y -c conda-forge scikit-image
conda update -y h5py
conda update -y pillow
yes | pip install opencv-python
yes | pip install jarvis-md
yes | pip install -U -i https://test.pypi.org/simple/ biondi==0.1.6.0.1
yes | pip install pyCompare
